"use client";
import { useEffect,type ButtonHTMLAttributes,type ReactNode } from "react";
import styles from "./ui.module.css";
export const cx=(...values:Array<string|false|null|undefined>)=>values.filter(Boolean).join(" ");
export function Button({variant="primary",loading,children,className,disabled,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"outline"|"danger"|"ghost";loading?:boolean}){return <button className={cx(styles.button,styles[variant],className)} disabled={disabled||loading} {...props}>{loading&&<span className={styles.spinner} aria-hidden="true"/>}{children}</button>}
export function Card({children,className}:{children:ReactNode;className?:string}){return <section className={cx(styles.card,className)}>{children}</section>}
export function TableShell({children,className}:{children:ReactNode;className?:string}){return <div className={cx(styles.tableShell,className)}>{children}</div>}
const badgeTone:Record<string,string>={SUCCESS:"success",ACTIVE:"success",WARNING:"warning",PENDING:"warning",QUEUED:"info",PROCESSING:"info",ERROR:"danger",REVOKED:"danger",SUSPENDED:"danger",NOT_CONFIGURED:"neutral"};
export function StatusBadge({status,label}:{status:string;label?:string}){return <span className={cx(styles.badge,styles[badgeTone[status]??"neutral"])}>{label??status}</span>}
export function Alert({children,tone="info"}:{children:ReactNode;tone?:"info"|"success"|"warning"|"danger"}){return <div className={cx(styles.alert,styles[tone])} role={tone==="danger"?"alert":"status"}>{children}</div>}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className={styles.pageHeader}><div>{eyebrow&&<p className={styles.eyebrow}>{eyebrow}</p>}<h1>{title}</h1>{description&&<p className={styles.description}>{description}</p>}</div>{actions&&<div className={styles.headerActions}>{actions}</div>}</header>}
export function SectionHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className={styles.sectionHeader}><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
export function StatCard({label,value,hint,icon}:{label:string;value:string|number;hint?:string;icon?:ReactNode}){return <Card className={styles.statCard}><div className={styles.statIcon}>{icon}</div><div><span>{label}</span><strong>{value}</strong>{hint&&<small>{hint}</small>}</div></Card>}
export function EmptyState({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className={styles.empty}><div className={styles.emptyIcon} aria-hidden="true">○</div><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>}
export function Skeleton({className}:{className?:string}){return <span className={cx(styles.skeleton,className)} aria-hidden="true"/>}
export function Field({label,helper,error,children}:{label:string;helper?:string;error?:string;children:ReactNode}){return <label className={styles.field}><span>{label}</span>{children}{error?<small className={styles.fieldError}>{error}</small>:helper?<small>{helper}</small>:null}</label>}
export function Dialog({open,title,children,actions,onClose}:{open:boolean;title:string;children:ReactNode;actions?:ReactNode;onClose:()=>void}){useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open,onClose]);if(!open)return null;return <div className={styles.backdrop} onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><h2 id="dialog-title">{title}</h2><Button variant="ghost" type="button" onClick={onClose} aria-label="Đóng hộp thoại">×</Button></header><div className={styles.dialogBody}>{children}</div>{actions&&<footer>{actions}</footer>}</section></div>}
