"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useCurrentUser } from "../../../components/auth-shell";
import { apiJson } from "../../../lib/api";
import styles from "./users.module.css";
type User={id:string;username:string;displayName:string;role:"ADMIN"|"USER";isActive:boolean;createdAt:string;updatedAt:string};
function password(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%*+-_";const max=Math.floor(256/chars.length)*chars.length;const output:string[]=[];while(output.length<20){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);for(const byte of bytes){if(byte<max)output.push(chars[byte%chars.length]);if(output.length===20)break}}return output.join("")}
export default function AdminUsersPage(){const me=useCurrentUser();const [users,setUsers]=useState<User[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [form,setForm]=useState({username:"",displayName:"",role:"USER" as User["role"],password:""});const [temporary,setTemporary]=useState("");const load=useCallback(async()=>{setLoading(true);try{setUsers(await apiJson<User[]>("/admin/users"));setError("")}catch(e){setError((e as {status?:number}).status===403?"Bạn không có quyền thực hiện thao tác này.":"Không thể tải danh sách tài khoản.")}finally{setLoading(false)}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);if(me?.role!=="ADMIN")return <main className={styles.page}><section className={styles.state}><h1>Không có quyền truy cập</h1><p>Bạn không có quyền thực hiện thao tác này.</p></section></main>;
const generated=()=>{const value=password();setForm({...form,password:value});setTemporary(value)};const create=async(e:FormEvent)=>{e.preventDefault();setError("");try{await apiJson("/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});setNotice("Tài khoản đã được tạo. Hãy lưu mật khẩu tạm ngay bây giờ.");setTemporary(form.password);setForm({username:"",displayName:"",role:"USER",password:""});await load()}catch(e){const x=e as {status?:number;body?:{errorCode?:string}};setError(x.body?.errorCode==="USERNAME_ALREADY_EXISTS"?"Tên đăng nhập đã tồn tại.":x.status===403?"Bạn không có quyền thực hiện thao tác này.":"Không thể tạo tài khoản.")}};
const update=async(user:User,patch:Partial<Pick<User,"displayName"|"role"|"isActive">>)=>{setError("");try{await apiJson(`/admin/users/${user.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});setNotice("Đã cập nhật tài khoản.");await load()}catch(e){const x=e as {body?:{errorCode?:string}};const code=x.body?.errorCode;setError(code==="CANNOT_DEACTIVATE_SELF"?"Bạn không thể tự vô hiệu hóa tài khoản của mình.":code==="CANNOT_CHANGE_OWN_ROLE"?"Bạn không thể tự thay đổi vai trò của mình.":code==="LAST_ACTIVE_ADMIN_REQUIRED"?"Hệ thống phải luôn có ít nhất một tài khoản quản trị đang hoạt động.":"Không thể cập nhật tài khoản.")}};
const reset=async(user:User)=>{const value=password();setError("");try{await apiJson(`/admin/users/${user.id}/reset-password`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({newPassword:value})});setTemporary(value);setNotice(`Đã đặt lại mật khẩu cho ${user.username}. Các phiên đăng nhập cũ đã bị thu hồi.`)}catch{setError("Không thể đặt lại mật khẩu.")}};
return <main className={styles.page}><header><p className={styles.brand}>Quản trị hệ thống</p><h1>Quản lý tài khoản</h1><p>Tạo tài khoản, thay đổi vai trò, kích hoạt hoặc vô hiệu hóa. Không có thao tác xóa tài khoản.</p></header><section className={styles.panel}><h2>Tạo tài khoản</h2><form onSubmit={create}><label>Tên đăng nhập<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required/></label><label>Tên hiển thị<input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} required/></label><label>Vai trò<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as User["role"]})}><option value="USER">Người dùng</option><option value="ADMIN">Người quản trị</option></select></label><label>Mật khẩu tạm<input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={10} required/></label><button type="button" className={styles.secondary} onClick={generated}>Tạo mật khẩu mạnh</button><button>Tạo tài khoản</button></form></section>{temporary&&<section className={styles.temporary} role="status"><strong>Mật khẩu tạm — chỉ hiển thị trong phiên này:</strong><code>{temporary}</code><button onClick={()=>setTemporary("")}>Đã lưu mật khẩu</button></section>}{notice&&<p className={styles.notice}>{notice}</p>}{error&&<p className={styles.error} role="alert">{error}</p>}{loading?<section className={styles.state}>Đang tải tài khoản...</section>:<section className={styles.tableWrap}><table><thead><tr><th>Tên đăng nhập</th><th>Tên hiển thị</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.username}</td><td><input aria-label={`Tên hiển thị ${user.username}`} defaultValue={user.displayName} onBlur={e=>e.target.value!==user.displayName&&void update(user,{displayName:e.target.value})}/></td><td><select aria-label={`Vai trò ${user.username}`} value={user.role} onChange={e=>void update(user,{role:e.target.value as User["role"]})}><option value="USER">Người dùng</option><option value="ADMIN">Người quản trị</option></select></td><td>{user.isActive?"Đang hoạt động":"Đã vô hiệu hóa"}</td><td>{new Date(user.createdAt).toLocaleDateString("vi-VN")}</td><td><div className={styles.actions}>{user.isActive?<button onClick={()=>{if(confirm("Vô hiệu hóa tài khoản này? Người dùng sẽ không thể đăng nhập cho đến khi được kích hoạt lại."))void update(user,{isActive:false})}}>Vô hiệu hóa</button>:<button onClick={()=>void update(user,{isActive:true})}>Kích hoạt lại</button>}<button onClick={()=>void reset(user)}>Đặt lại mật khẩu</button></div></td></tr>)}</tbody></table></section>}</main>}
