import assert from "node:assert/strict";
import test from "node:test";
import { LazadaCredentialLifecycle, LazadaLifecycleError } from "./lazada-credential-lifecycle.js";
import { LazadaHttpError } from "./lazada-errors.js";
import { LazadaOrderClient, LazadaOrderClientError, type LazadaAccessTokenLifecycle, type LazadaOrderHttpClient } from "./lazada-order-client.js";
import { LAZADA_GET_ORDER_FIXTURE, LAZADA_GET_ORDER_ITEMS_FIXTURE, LAZADA_GET_ORDERS_FIXTURE, LAZADA_GET_MULTIPLE_ORDER_ITEMS_FIXTURE } from "./lazada-order-fixtures.js";
import type { LazadaLowLevelRequest, LazadaResponseEnvelope } from "./lazada-http-client-core.js";
import type { DistributedLockProvider, MarketplaceCredentialCrypto, MarketplaceLifecycleConnectionRepository } from "./lifecycle-contracts.js";

const TOKEN = "TEST_LAZADA_ACCESS_TOKEN";
class Credentials implements LazadaAccessTokenLifecycle {
  calls = 0; error?: Error; token = TOKEN;
  async ensureValidAccessToken() { this.calls++; if (this.error) throw this.error; return { accessToken: this.token, externalShopId: "vn:42", accessTokenExpiresAt: "2026-10-01T00:00:00.000Z" }; }
}
class Http implements LazadaOrderHttpClient {
  requests: LazadaLowLevelRequest[] = [];
  handler: (request: LazadaLowLevelRequest, index: number) => LazadaResponseEnvelope = () => LAZADA_GET_ORDERS_FIXTURE;
  async request<T = unknown, E extends LazadaResponseEnvelope<T> = LazadaResponseEnvelope<T>>(request: LazadaLowLevelRequest) { this.requests.push(request); const envelope = this.handler(request, this.requests.length - 1) as E; return { data: envelope.data as T | undefined, envelope, requestId: envelope.request_id }; }
}
function client() { const http = new Http(), credentials = new Credentials(); return { http, credentials, client: new LazadaOrderClient(http, credentials) }; }
const createWindow = { mode: "CREATE_TIME", from: "2026-09-01T00:00:00+07:00", to: "2026-09-02T00:00:00+07:00" } as const;
const updateWindow = { mode: "UPDATE_TIME", from: "2026-09-01T00:00:00Z", to: "2026-09-02T00:00:00Z" } as const;
function order(orderId: string, timestamp: string = createWindow.from) { return { order_id: orderId, created_at: timestamp, updated_at: timestamp, statuses: ["pending"] }; }
function envelope(orders: unknown[], total = orders.length, requestId = "req-list") { return { code: "0", request_id: requestId, data: { count: String(orders.length), countTotal: String(total), orders } }; }

test("lists one page with CREATE_TIME exact params, token and request ID", async () => { const x = client(); const page = await x.client.listOrders({ connectionId: "c1", window: createWindow, limit: 100, offset: 0, status: "all" }); assert.equal(page.requestId, "fixture-request-orders"); assert.equal(x.http.requests.length, 1); const req = x.http.requests[0]!; assert.equal(req.apiPath, "/orders/get"); assert.equal(req.operation, "listOrders"); assert.equal(req.accessToken, TOKEN); assert.deepEqual(req.params, { limit: 100, offset: 0, sort_by: "created_at", sort_direction: "ASC", status: "all", created_after: createWindow.from, created_before: createWindow.to }); });
test("UPDATE_TIME emits only exact update filters", async () => { const x = client(); await x.client.listOrders({ connectionId: "c1", window: updateWindow }); const params = x.http.requests[0]!.params!; assert.equal(params.update_after, updateWindow.from); assert.equal(params.update_before, updateWindow.to); assert.equal(params.created_after, undefined); assert.equal(params.created_before, undefined); });
test("invalid mixed/unknown mode and timestamps fail before lifecycle/provider", async () => { const x = client(); await assert.rejects(x.client.listOrders({ connectionId: "c1", window: { ...createWindow, mode: "MIXED" as "CREATE_TIME" } }), LazadaOrderClientError); await assert.rejects(x.client.listOrders({ connectionId: "c1", window: { ...createWindow, from: "2026-09-01 00:00:00" } }), LazadaOrderClientError); assert.equal(x.credentials.calls, 0); assert.equal(x.http.requests.length, 0); });
test("preserves +07:00 and inclusive boundary records without local filtering", async () => { const x = client(); x.http.handler = () => envelope([order("1", createWindow.from), order("2", createWindow.to)]); const result = await x.client.listOrders({ connectionId: "c1", window: createWindow }); assert.deepEqual(result.orders.map((v) => v.order_id), ["1", "2"]); assert.equal(x.http.requests[0]!.params!.created_after, createWindow.from); });
test("validates limit and offset locally", async () => { for (const bad of [0, 101, 1.5]) { const x = client(); await assert.rejects(x.client.listOrders({ connectionId: "c1", window: createWindow, limit: bad }), LazadaOrderClientError); assert.equal(x.http.requests.length, 0); } for (const bad of [-1, 5001, 1.5]) { const x = client(); await assert.rejects(x.client.listOrders({ connectionId: "c1", window: createWindow, offset: bad }), LazadaOrderClientError); assert.equal(x.http.requests.length, 0); } });
test("empty provider list is a successful empty page", async () => { const x = client(); x.http.handler = () => envelope([], 0); const page = await x.client.listOrders({ connectionId: "c1", window: createWindow }); assert.deepEqual(page.orders, []); assert.equal(page.count, 0); });
test("collects 230 orders over offsets 0,100,200", async () => { const x = client(); x.http.handler = (request) => { const start = Number(request.params!.offset); const size = Math.min(100, 230 - start); return envelope(Array.from({ length: size }, (_, i) => order(String(start + i + 1))), 230, `req-${start}`); }; const result = await x.client.listAllOrdersInWindow({ connectionId: "c1", window: createWindow }); assert.equal(result.orders.length, 230); assert.deepEqual(x.http.requests.map((r) => r.params!.offset), [0, 100, 200]); assert.deepEqual(result.requestIds, ["req-0", "req-100", "req-200"]); });
test("deduplicates exact IDs across pages, preserves first snapshot and reports duplicate", async () => { const x = client(); x.http.handler = (request) => Number(request.params!.offset) === 0 ? envelope([order("1"), order("2")], 3) : envelope([{ ...order("2"), statuses: ["shipped"] }, order("3")], 3); const result = await x.client.listAllOrdersInWindow({ connectionId: "c1", window: createWindow, limit: 2 }); assert.deepEqual(result.orders.map((o) => o.order_id), ["1", "2", "3"]); assert.deepEqual(result.orders[1]!.statuses, ["pending"]); assert.deepEqual(result.duplicateOrderIds, ["2"]); });
test("detects non-progressing duplicate pagination", async () => { const x = client(); x.http.handler = () => envelope([order("1")], 3); await assert.rejects(x.client.listAllOrdersInWindow({ connectionId: "c1", window: createWindow, limit: 1 }), (e: unknown) => e instanceof LazadaOrderClientError && e.code === "LAZADA_PAGINATION_NON_PROGRESS"); assert.equal(x.http.requests.length, 2); });
test("fails instead of traversing beyond offset 5000", async () => { const x = client(); x.http.handler = (request) => { const start = Number(request.params!.offset); return envelope(Array.from({ length: 100 }, (_, i) => order(String(start + i + 1))), 5101); }; await assert.rejects(x.client.listAllOrdersInWindow({ connectionId: "c1", window: createWindow }), (e: unknown) => e instanceof LazadaOrderClientError && e.code === "LAZADA_WINDOW_TOO_LARGE"); assert.equal(x.http.requests.at(-1)!.params!.offset, 5000); assert.equal(x.http.requests.length, 51); });
test("getOrder preserves a large string ID exactly", async () => { const x = client(); x.http.handler = () => ({ ...LAZADA_GET_ORDER_FIXTURE, data: { ...LAZADA_GET_ORDER_FIXTURE.data, order_id: "9007199254740993" } }); const result = await x.client.getOrder("c1", "9007199254740993"); assert.equal(result.order.order_id, "9007199254740993"); assert.equal(x.http.requests[0]!.params!.order_id, "9007199254740993"); assert.equal(x.http.requests[0]!.operation, "getOrder"); });
test("getOrderItems preserves repeated units and distinct item identities", async () => { const x = client(); x.http.handler = () => LAZADA_GET_ORDER_ITEMS_FIXTURE; const result = await x.client.getOrderItems("c1", "9007199254740993"); assert.equal(result.items.length, 2); assert.equal(result.items[0]!.sku, result.items[1]!.sku); assert.notEqual(result.items[0]!.order_item_id, result.items[1]!.order_item_id); });
test("multiple items deduplicates input order, preserves first order and grouping", async () => { const x = client(); x.http.handler = () => LAZADA_GET_MULTIPLE_ORDER_ITEMS_FIXTURE; const result = await x.client.getMultipleOrderItems("c1", ["9007199254740993", "2", "9007199254740993"]); assert.deepEqual(result.requestedOrderIds, ["9007199254740993", "2"]); assert.equal(x.http.requests[0]!.params!.order_ids, "[9007199254740993,2]"); assert.equal(result.groups.length, 1); });
test("multiple items accepts 50 and rejects 51 or empty before provider", async () => { const fifty = Array.from({ length: 50 }, (_, i) => String(i + 1)); const ok = client(); ok.http.handler = () => ({ code: "0", data: [] }); await ok.client.getMultipleOrderItems("c1", fifty); assert.equal(ok.http.requests.length, 1); for (const values of [[], [...fifty, "51"]]) { const x = client(); await assert.rejects(x.client.getMultipleOrderItems("c1", values), LazadaOrderClientError); assert.equal(x.credentials.calls, 0); assert.equal(x.http.requests.length, 0); } });
test("missing multiple-items group is not fabricated", async () => { const x = client(); x.http.handler = () => ({ code: "0", data: [{ order_id: "1", order_items: [] }, { order_id: "3", order_items: [] }] }); const result = await x.client.getMultipleOrderItems("c1", ["1", "2", "3"]); assert.deepEqual(result.groups.map((g) => g.order_id), ["1", "3"]); assert.deepEqual(result.requestedOrderIds, ["1", "2", "3"]); });
test("malformed responses and unsafe numeric IDs fail coherently", async () => { for (const response of [envelope([{ created_at: "x", updated_at: "y", statuses: [] }]), envelope([{ ...order("1"), statuses: "pending" }]), envelope([{ ...order("1"), order_id: 9007199254740992 }]), { code: "0", data: { count: "bad", orders: [] } }]) { const x = client(); x.http.handler = () => response as LazadaResponseEnvelope; await assert.rejects(x.client.listOrders({ connectionId: "c1", window: createWindow })); } });
test("provider diagnostics contain no token or synthetic PII", async () => { const x = client(); x.http.handler = () => { throw new LazadaHttpError({ provider: "LAZADA", code: "LAZADA_PROVIDER_ERROR", operation: "listOrders", apiPath: "/orders/get", retryable: false, message: "Rejected", providerCode: "E", requestId: "req-safe", httpStatus: 400 }); }; await assert.rejects(x.client.listOrders({ connectionId: "c1", window: createWindow }), (e: unknown) => { const text = JSON.stringify(e); return !text.includes(TOKEN) && !text.includes("09****123") && !text.includes("address"); }); });
test("valid external token is used internally; expired external token propagates without request", async () => { const valid = client(); await valid.client.listOrders({ connectionId: "external", window: createWindow }); assert.equal(valid.http.requests[0]!.accessToken, TOKEN); assert.equal(JSON.stringify(await valid.client.listOrders({ connectionId: "external", window: createWindow })).includes(TOKEN), false); const expired = client(); expired.credentials.error = new LazadaLifecycleError("EXTERNAL_ACCESS_TOKEN_EXPIRED", false); await assert.rejects(expired.client.listOrders({ connectionId: "external", window: createWindow }), (e: unknown) => e instanceof LazadaLifecycleError && e.code === "EXTERNAL_ACCESS_TOKEN_EXPIRED"); assert.equal(expired.http.requests.length, 0); });
test("OAuth-owned expired credential refreshes through lifecycle then OrderClient uses new token", async () => { let envelopeValue = JSON.stringify({ accessToken: "OLD", refreshToken: "REFRESH", tokenExpiresAt: "2026-09-29T00:00:00.000Z", refreshTokenExpiresAt: "2026-10-30T00:00:00.000Z", providerMetadata: { country: "vn", sellerId: "42", credentialSource: "OAUTH", refreshOwnership: "ECOMKIT" } }); const repository: MarketplaceLifecycleConnectionRepository = { getById: async () => ({ connectionId: "c1", platform: "LAZADA", externalShopId: "vn:42", status: "ACTIVE", credentialEnvelope: envelopeValue }), replaceCredentialEnvelope: async ({ credentialEnvelope }) => { envelopeValue = credentialEnvelope; }, markReauthRequired: async () => undefined }; const crypto: MarketplaceCredentialCrypto = { encrypt: JSON.stringify, decrypt: JSON.parse }; const locks: DistributedLockProvider = { acquire: async (key) => ({ kind: "acquired", key, release: async () => undefined }) }; let refreshCalls = 0; const lifecycle = new LazadaCredentialLifecycle(repository, crypto, locks, { refresh: async () => { refreshCalls++; return { accessToken: "NEW", refreshToken: "NEW_REFRESH", expiresIn: 3600, refreshExpiresIn: 100000 }; } }, { now: () => new Date("2026-09-30T00:00:00.000Z") }, { refreshSkewSeconds: 300, refreshLockTtlMs: 30000 }); const http = new Http(); const orderClient = new LazadaOrderClient(http, lifecycle); await orderClient.listOrders({ connectionId: "c1", window: createWindow }); assert.equal(refreshCalls, 1); assert.equal(http.requests[0]!.accessToken, "NEW"); });

console.log("Lazada OrderClient foundation tests passed");
