import assert from "node:assert/strict";
import test from "node:test";
import type { MarketplaceLifecycleConnection, MarketplaceLifecycleConnectionRepository, MarketplaceCredentialCrypto, DistributedLockProvider } from "./lifecycle-contracts.js";
import { LazadaCredentialLifecycle, LazadaLifecycleError, type LazadaRefreshResult, type LazadaTokenRefreshClient } from "./lazada-credential-lifecycle.js";

const now = Date.parse("2026-09-30T00:00:00.000Z");
const old = { accessToken: "TEST_LAZADA_ACCESS_TOKEN_OLD", refreshToken: "TEST_LAZADA_REFRESH_TOKEN_OLD", tokenExpiresAt: new Date(now - 1).toISOString(), refreshTokenExpiresAt: new Date(now + 10_000_000).toISOString(), providerMetadata: { country: "vn", sellerId: "42", credentialSource: "OAUTH", refreshOwnership: "ECOMKIT" } };

class Repo implements MarketplaceLifecycleConnectionRepository {
  row: MarketplaceLifecycleConnection = { connectionId: "c1", platform: "LAZADA", externalShopId: "vn:42", status: "ACTIVE", credentialEnvelope: JSON.stringify(old) };
  writes = 0; failWrite = false;
  async getById(id: string) { return id === this.row.connectionId ? this.row : null; }
  async replaceCredentialEnvelope(input: { connectionId: string; credentialEnvelope: string }) { if (this.failWrite) throw new Error("db"); this.writes++; this.row = { ...this.row, credentialEnvelope: input.credentialEnvelope }; }
  async markReauthRequired() { this.row = { ...this.row, status: "REAUTH_REQUIRED" }; }
}
const crypto: MarketplaceCredentialCrypto = { encrypt: JSON.stringify, decrypt: JSON.parse };
class Locks implements DistributedLockProvider { acquisitions = 0; busy = false; async acquire(key: string) { this.acquisitions++; if (this.busy) return { kind: "busy" } as const; return { kind: "acquired", key, release: async () => undefined } as const; } }
class Refresh implements LazadaTokenRefreshClient { calls = 0; fail?: LazadaLifecycleError; async refresh(): Promise<LazadaRefreshResult> { this.calls++; if (this.fail) throw this.fail; return { accessToken: "TEST_LAZADA_ACCESS_TOKEN_NEW", refreshToken: "TEST_LAZADA_REFRESH_TOKEN_NEW", expiresIn: 3600, refreshExpiresIn: 999999, requestId: "req-1" }; } }
function lifecycle(repo = new Repo(), locks = new Locks(), refresh = new Refresh(), cryptoPort = crypto) { return { repo, locks, refresh, core: new LazadaCredentialLifecycle(repo, cryptoPort, locks, refresh, { now: () => new Date(now) }, { refreshSkewSeconds: 300, refreshLockTtlMs: 30_000 }) }; }

test("reuses a valid token without lock or refresh", async () => { const x = lifecycle(); x.repo.row = { ...x.repo.row, credentialEnvelope: JSON.stringify({ ...old, tokenExpiresAt: new Date(now + 600_000).toISOString() }) }; assert.equal((await x.core.ensureValidAccessToken("c1")).accessToken, old.accessToken); assert.equal(x.refresh.calls, 0); assert.equal(x.locks.acquisitions, 0); assert.equal(x.repo.writes, 0); });
test("rotates both tokens and does not extend original refresh expiry", async () => { const x = lifecycle(); const originalExpiry = old.refreshTokenExpiresAt; assert.equal((await x.core.ensureValidAccessToken("c1")).accessToken, "TEST_LAZADA_ACCESS_TOKEN_NEW"); const stored = JSON.parse(x.repo.row.credentialEnvelope!); assert.equal(stored.refreshToken, "TEST_LAZADA_REFRESH_TOKEN_NEW"); assert.equal(stored.refreshTokenExpiresAt, originalExpiry); assert.equal(x.refresh.calls, 1); assert.equal(x.repo.writes, 1); });
test("external ownership never locks or refreshes", async () => { const x = lifecycle(); x.repo.row = { ...x.repo.row, credentialEnvelope: JSON.stringify({ ...old, refreshToken: undefined, refreshTokenExpiresAt: undefined, providerMetadata: { ...old.providerMetadata, credentialSource: "EXTERNAL_IMPORT", refreshOwnership: "EXTERNAL" } }) }; await assert.rejects(x.core.ensureValidAccessToken("c1"), (e: unknown) => e instanceof LazadaLifecycleError && e.code === "EXTERNAL_ACCESS_TOKEN_EXPIRED"); assert.equal(x.refresh.calls, 0); assert.equal(x.locks.acquisitions, 0); });
test("missing and expired refresh tokens fail before provider call", async () => { for (const credential of [{ ...old, refreshToken: undefined }, { ...old, refreshTokenExpiresAt: new Date(now - 1).toISOString() }]) { const x = lifecycle(); x.repo.row = { ...x.repo.row, credentialEnvelope: JSON.stringify(credential) }; await assert.rejects(x.core.ensureValidAccessToken("c1"), LazadaLifecycleError); assert.equal(x.refresh.calls, 0); } });
test("provider failure and malformed success preserve old envelope", async () => { const x = lifecycle(); const before = x.repo.row.credentialEnvelope; x.refresh.fail = new LazadaLifecycleError("LAZADA_REFRESH_FAILED", true, "req-x"); await assert.rejects(x.core.ensureValidAccessToken("c1"), (e: unknown) => e instanceof LazadaLifecycleError && e.retryable && e.requestId === "req-x"); assert.equal(x.repo.row.credentialEnvelope, before); const y = lifecycle(); y.refresh.refresh = async () => ({ accessToken: "new" }); await assert.rejects(y.core.ensureValidAccessToken("c1"), (e: unknown) => e instanceof LazadaLifecycleError && e.code === "LAZADA_REFRESH_RESPONSE_INVALID"); assert.equal(y.repo.writes, 0); });
test("encryption and repository failures never report success or leak tokens", async () => { const badCrypto: MarketplaceCredentialCrypto = { encrypt: () => { throw new Error("TEST_LAZADA_ACCESS_TOKEN_NEW"); }, decrypt: JSON.parse }; const a = lifecycle(new Repo(), new Locks(), new Refresh(), badCrypto); await assert.rejects(a.core.ensureValidAccessToken("c1"), (e: unknown) => e instanceof LazadaLifecycleError && !e.message.includes("TOKEN_NEW")); const b = lifecycle(); b.repo.failWrite = true; await assert.rejects(b.core.ensureValidAccessToken("c1"), (e: unknown) => e instanceof LazadaLifecycleError && e.code === "LAZADA_CREDENTIAL_PERSIST_FAILED" && !e.retryable); });
test("same-connection API/Worker race refreshes once", async () => { const repo = new Repo(), refresh = new Refresh(); let held = false; const locks: DistributedLockProvider = { acquire: async (key) => { if (held) return { kind: "busy" }; held = true; return { kind: "acquired", key, release: async () => { held = false; } }; } }; const api = new LazadaCredentialLifecycle(repo, crypto, locks, refresh, { now: () => new Date(now) }, { refreshSkewSeconds: 300, refreshLockTtlMs: 30_000 }); const worker = new LazadaCredentialLifecycle(repo, crypto, locks, refresh, { now: () => new Date(now) }, { refreshSkewSeconds: 300, refreshLockTtlMs: 30_000 }); const [a, b] = await Promise.all([api.ensureValidAccessToken("c1"), worker.ensureValidAccessToken("c1")]); assert.equal(a.accessToken, b.accessToken); assert.equal(refresh.calls, 1); });
test("cross-connection locks are independent", async () => { const repo = new Repo(); const rows = new Map<string, MarketplaceLifecycleConnection>([["a", { ...repo.row, connectionId: "a" }], ["b", { ...repo.row, connectionId: "b", externalShopId: "vn:43", credentialEnvelope: JSON.stringify({ ...old, providerMetadata: { ...old.providerMetadata, sellerId: "43" } }) }]]); repo.getById = async (id) => rows.get(id) ?? null; repo.replaceCredentialEnvelope = async ({ connectionId, credentialEnvelope }) => { rows.set(connectionId, { ...rows.get(connectionId)!, credentialEnvelope }); }; const keys: string[] = []; const locks: DistributedLockProvider = { acquire: async (key) => { keys.push(key); return { kind: "acquired", key, release: async () => undefined }; } }; const refresh = new Refresh(); const core = new LazadaCredentialLifecycle(repo, crypto, locks, refresh, { now: () => new Date(now) }, { refreshSkewSeconds: 0, refreshLockTtlMs: 1000 }); await Promise.all([core.ensureValidAccessToken("a"), core.ensureValidAccessToken("b")]); assert.equal(new Set(keys).size, 2); assert.equal(refresh.calls, 2); });

console.log("lazada credential lifecycle tests passed");
