import assert from "node:assert/strict";
import test from "node:test";
import type { LazadaRawOrder, LazadaRawOrderItem } from "./lazada-order-contract.js";
import { LAZADA_CANONICAL_24_COLUMN_MAPPING, LazadaNormalizationError, LazadaNormalizer } from "./lazada-normalizer.js";

const ORDER_ID = "9007199254740993";
function order(overrides: Record<string, unknown> = {}): LazadaRawOrder { return { order_id: ORDER_ID, order_number: ORDER_ID, created_at: "2026-09-01T08:00:00+07:00", updated_at: "2026-09-01T09:00:00+07:00", statuses: ["pending"], price: "100.50", shipping_fee: "5.25", voucher: "2.00", payment_method: "COD", customer_first_name: "N***", customer_last_name: "A***", buyer_note: "Masked note", address_shipping: { first_name: "N***", phone: "09****123", address1: "***", city: "H***" }, ...overrides } as LazadaRawOrder; }
function item(id: string, overrides: Record<string, unknown> = {}): LazadaRawOrderItem { return { order_item_id: id, order_id: ORDER_ID, status: "pending", sku: "PLATFORM-SKU", shop_sku: "SELLER-SKU", name: "Synthetic product", variation: "Red", paid_price: "49.99", currency: "VND", ...overrides } as LazadaRawOrderItem; }
const normalizer = new LazadaNormalizer();

test("is deterministic and maps exact large order identity and timestamps", () => { const input = { order: order(), items: [item("9007199254741001")] }; assert.deepEqual(normalizer.normalize(input), normalizer.normalize(input)); const out = normalizer.normalize(input); assert.equal(out.marketplaceOrderId, ORDER_ID); assert.equal(out.rawOrderCode, ORDER_ID); assert.equal(out.providerCreatedAt, "2026-09-01T01:00:00.000Z"); assert.equal(out.providerUpdatedAt, "2026-09-01T02:00:00.000Z"); });
test("single status maps directly without translating provider value", () => { const out = normalizer.normalize({ order: order({ statuses: ["future_provider_status"] }), items: [] }); assert.equal(out.rawProviderStatus, "future_provider_status"); assert.deepEqual(out.providerMetadata!.providerStatuses, ["future_provider_status"]); });
test("mixed statuses have no fake order status and preserve distinct values", () => { const out = normalizer.normalize({ order: order({ statuses: ["pending", "ready_to_ship"] }), items: [] }); assert.equal(out.rawProviderStatus, undefined); assert.deepEqual(out.providerMetadata!.providerStatuses, ["pending", "ready_to_ship"]); assert.equal(JSON.stringify(out).includes("MIXED"), false); });
test("duplicate statuses collapse to one effective provider status", () => { const out = normalizer.normalize({ order: order({ statuses: ["pending", "pending"] }), items: [] }); assert.equal(out.rawProviderStatus, "pending"); assert.deepEqual(out.providerMetadata!.providerStatuses, ["pending"]); });
test("repeated SKU units remain two items with quantity one and exact IDs", () => { const out = normalizer.normalize({ order: order(), items: [item("9007199254741001"), item("9007199254741002")] }); assert.equal(out.items!.length, 2); assert.deepEqual(out.items!.map((v) => [v.externalItemId, v.sellerSku, v.platformSku, v.quantity]), [["9007199254741001", "SELLER-SKU", "PLATFORM-SKU", 1], ["9007199254741002", "SELLER-SKU", "PLATFORM-SKU", 1]]); });
test("maps paid price strictly and preserves documented money without calculations", () => { const out = normalizer.normalize({ order: order(), items: [item("1")] }); assert.equal(out.items![0]!.unitPrice, "49.99"); assert.equal(out.providerMetadata!.totalAmount, "100.50"); assert.equal(out.providerMetadata!.shippingFee, "5.25"); assert.equal(out.providerMetadata!.voucherAmount, "2.00"); });
test("rejects malformed optional money instead of returning zero", () => { assert.throws(() => normalizer.normalize({ order: order({ price: "abc" }), items: [] }), (e: unknown) => e instanceof LazadaNormalizationError && e.code === "LAZADA_NORMALIZATION_VALUE_INVALID"); assert.throws(() => normalizer.normalize({ order: order(), items: [item("1", { paid_price: Number.NaN })] }), LazadaNormalizationError); });
test("does not assume currency when order has none", () => { const out = normalizer.normalize({ order: order(), items: [item("1", { currency: undefined })] }); assert.equal(out.currency, undefined); });
test("preserves masked PII subset and accepts missing PII without inference", () => { const masked = normalizer.normalize({ order: order(), items: [] }); assert.equal((masked.providerMetadata!.shippingAddress as Record<string, unknown>).phone, "09****123"); const missing = normalizer.normalize({ order: order({ customer_first_name: undefined, customer_last_name: undefined, address_shipping: undefined }), items: [] }); assert.equal(missing.providerMetadata!.customerFirstName, undefined); assert.equal(missing.providerMetadata!.shippingAddress, undefined); });
test("rejects item parent mismatch", () => { assert.throws(() => normalizer.normalize({ order: order(), items: [item("1", { order_id: "2" })] }), (e: unknown) => e instanceof LazadaNormalizationError && e.code === "LAZADA_NORMALIZATION_ITEM_ORDER_MISMATCH"); });
test("rejects duplicate order_item_id", () => { assert.throws(() => normalizer.normalize({ order: order(), items: [item("1"), item("1")] }), (e: unknown) => e instanceof LazadaNormalizationError && e.code === "LAZADA_NORMALIZATION_DUPLICATE_ITEM"); });
test("allows a verified empty item collection without fabricating items", () => { assert.deepEqual(normalizer.normalize({ order: order(), items: [] }).items, []); });
test("does not mutate raw order/items and ignores unknown fields", () => { const input = { order: order({ future_field: { nested: true } }), items: [item("1", { future_item_field: "x" })] }; const before = JSON.stringify(input); const out = normalizer.normalize(input); assert.equal(JSON.stringify(input), before); assert.equal(JSON.stringify(out).includes("future_field"), false); assert.equal(JSON.stringify(out).includes("future_item_field"), false); });
test("safe errors contain no PII or raw payload", () => { try { normalizer.normalize({ order: order({ updated_at: "invalid", secret_phone: "0900000000" }), items: [] }); assert.fail("expected error"); } catch (error) { assert.ok(error instanceof LazadaNormalizationError); const safe = JSON.stringify(error.toJSON()); assert.equal(safe.includes("0900000000"), false); assert.equal(safe.includes("09****123"), false); } });
test("24-column mapping covers every current canonical export column once", () => { assert.equal(LAZADA_CANONICAL_24_COLUMN_MAPPING.length, 24); assert.equal(new Set(LAZADA_CANONICAL_24_COLUMN_MAPPING.map(([column]) => column)).size, 24); const unauthorized = LAZADA_CANONICAL_24_COLUMN_MAPPING.filter(([, , transform]) => !["DIRECT", "STRING_PRESERVE", "NULL"].includes(transform)); assert.deepEqual(unauthorized, []); });

console.log("Lazada normalizer policy tests passed");
