import type { ShopeeAccessCredential } from "./lifecycle-contracts.js";

export type ShopeeTimeRangeField = "create_time" | "update_time";
export type ShopeeOrderListItem = { order_sn?: string; order_status?: string; booking_sn?: string };
export type ShopeeOrderDetail = { order_sn?: string; region?: string; currency?: string; total_amount?: number; order_status?: string; create_time?: number; update_time?: number; recipient_address?: Record<string, unknown>; item_list?: Record<string, unknown>[]; [key: string]: unknown };
export type ShopeeOrderTransport = { list(credential: ShopeeAccessCredential, input: { timeRangeField: ShopeeTimeRangeField; timeFrom: number; timeTo: number; pageSize: number; cursor?: string }): Promise<{ orders?: ShopeeOrderListItem[]; more?: boolean; nextCursor?: string; requestId?: string }>; details(credential: ShopeeAccessCredential, orderSns: readonly string[]): Promise<{ orders?: ShopeeOrderDetail[]; requestId?: string }> };
export type ShopeeAccessCredentialProvider = { ensureValidAccessToken(connectionId: string): Promise<ShopeeAccessCredential> };
export class ShopeeOrderClientError extends Error { constructor(public readonly code: string, public readonly retryable: boolean, public readonly requestId?: string) { super(code); this.name = "ShopeeOrderClientError"; } toJSON() { return { name: this.name, code: this.code, retryable: this.retryable, ...(this.requestId ? { requestId: this.requestId } : {}) }; } }
const maxWindow = 15 * 86400;
export function splitShopeeOrderWindows(timeFrom: number, timeTo: number): Array<{ timeFrom: number; timeTo: number }> { if (!Number.isInteger(timeFrom) || !Number.isInteger(timeTo) || timeFrom >= timeTo) throw new ShopeeOrderClientError("SHOPEE_ORDER_INVALID_TIME_RANGE", false); const result=[]; for(let start=timeFrom;start<timeTo;start+=maxWindow) result.push({timeFrom:start,timeTo:Math.min(start+maxWindow,timeTo)}); return result; }
export function batchShopeeOrderSns(orderSns: readonly string[]): string[][] { if (!orderSns.length) throw new ShopeeOrderClientError("SHOPEE_ORDER_INVALID_ORDER_SN", false); return Array.from({length:Math.ceil(orderSns.length/50)},(_,i)=>[...orderSns.slice(i*50,i*50+50)]); }
export class ShopeeOrderClientCore {
  constructor(private readonly credentials: ShopeeAccessCredentialProvider, private readonly transport: ShopeeOrderTransport) {}
  async collectOrderSns(connectionId: string, input: { timeRangeField: ShopeeTimeRangeField; timeFrom: number; timeTo: number; pageSize?: number }): Promise<string[]> {
    if (input.timeRangeField !== "create_time" && input.timeRangeField !== "update_time") throw new ShopeeOrderClientError("SHOPEE_ORDER_INVALID_TIME_RANGE", false);
    const pageSize=input.pageSize??100; if(!Number.isInteger(pageSize)||pageSize<1||pageSize>100) throw new ShopeeOrderClientError("SHOPEE_ORDER_INVALID_PAGE_SIZE",false);
    const credential=await this.credentials.ensureValidAccessToken(connectionId), ids:string[]=[]; const seen=new Set<string>();
    for(const window of splitShopeeOrderWindows(input.timeFrom,input.timeTo)){ let cursor: string|undefined; const cursors=new Set<string>(); do { const page=await this.transport.list(credential,{timeRangeField:input.timeRangeField,timeFrom:window.timeFrom,timeTo:window.timeTo,pageSize,cursor}); for(const item of page.orders??[]){if(typeof item.order_sn!=="string"||!item.order_sn) throw new ShopeeOrderClientError("SHOPEE_ORDER_INVALID_ORDER_SN",false,page.requestId); if(!seen.has(item.order_sn)){seen.add(item.order_sn);ids.push(item.order_sn);}} if(page.more===true){if(!page.nextCursor||cursors.has(page.nextCursor)) throw new ShopeeOrderClientError("SHOPEE_ORDER_PAGINATION_INVALID",false,page.requestId);cursors.add(page.nextCursor);cursor=page.nextCursor;}else cursor=undefined; }while(cursor); }
    return ids;
  }
  async getOrderDetails(connectionId:string, orderSns:readonly string[]):Promise<ShopeeOrderDetail[]> { if(!orderSns.length)return []; const credential=await this.credentials.ensureValidAccessToken(connectionId), received=new Map<string,ShopeeOrderDetail>(); for(const batch of batchShopeeOrderSns(orderSns)){const response=await this.transport.details(credential,batch);for(const detail of response.orders??[]){if(typeof detail.order_sn!=="string"||!detail.order_sn||received.has(detail.order_sn)||!batch.includes(detail.order_sn))throw new ShopeeOrderClientError("SHOPEE_ORDER_DUPLICATE_DETAIL",false,response.requestId);received.set(detail.order_sn,detail);}} const missing=orderSns.find(id=>!received.has(id));if(missing)throw new ShopeeOrderClientError("SHOPEE_ORDER_MISSING_DETAIL",false);return orderSns.map(id=>received.get(id)!); }
}
