FROM node:24.21.0-bookworm-slim
WORKDIR /app
COPY package*.json ./
COPY web/package.json web/package.json
COPY api/package.json api/package.json
COPY worker/package.json worker/package.json
COPY shared/package.json shared/package.json
COPY database/package.json database/package.json
RUN npm ci --workspace web --include-workspace-root
COPY web web
COPY shared shared
RUN npm run build --workspace web
EXPOSE 3000
CMD ["npm", "run", "dev", "--workspace", "web"]
