"use client";
import {FormEvent,ReactNode,useCallback,useEffect,useState} from "react";
import {Alert,Button,Card,Dialog,EmptyState,Field,PageHeader,Skeleton,StatusBadge} from "../../components/ui/ui";
import {useCurrentUser} from "../../components/auth-shell";
import {apiJson} from "../../lib/api";
import styles from "./marketplaces.module.css";
type Config={partnerId:string;partnerSecretConfigured:boolean;environment:string;redirectUri:string;enabled:boolean};
type Connection={id:string;externalShopId:string;sellerId?:string;credentialSource:string;refreshOwnership?:string;accessTokenConfigured:boolean;refreshTokenConfigured?:boolean;accessTokenExpiresAt:string|null;liveApiStatus:string};
type Shopee={config:Config|null;encryptionReady:boolean;connections:Connection[]};
type LConfig={appKey:string;appSecretConfigured:boolean;redirectUri:string;enabled:boolean};
type Lazada={config:LConfig|null;encryptionReady:boolean;connections:Connection[]};
const err=(e:unknown,f:string)=>(e as{body?:{errorCode?:string}}).body?.errorCode??f;
const expiry=()=>{const d=new Date(Date.now()+3600000);return new Date(d.valueOf()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const oauthMessage=()=>{if(typeof window==="undefined")return "";const url=new URL(window.location.href),status=url.searchParams.get("shopeeOAuth");return status==="success"?"Đã kết nối Shopee và lưu thông tin xác thực an toàn.":status==="failed"?`Ủy quyền Shopee chưa hoàn tất (${url.searchParams.get("code")||"SHOPEE_OAUTH_FAILED"}).`:""};
export default function Page(){
 const user=useCurrentUser(),[shopee,setShopee]=useState<Shopee>({config:null,encryptionReady:false,connections:[]}),[lazada,setLazada]=useState<Lazada>({config:null,encryptionReady:false,connections:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[modal,setModal]=useState<string|null>(null),[shopeeLiveConnectionId,setShopeeLiveConnectionId]=useState<string>();
 const[lc,setLc]=useState({appKey:"",appSecret:"",redirectUri:"",enabled:true}),[le,setLe]=useState({sellerId:"",accessToken:"",accessTokenExpiresAt:expiry()}),[sc,setSc]=useState({environment:"sandbox",partnerId:"",partnerKey:"",redirectUri:"http://localhost:3001/api/marketplaces/shopee/oauth/callback",enabled:true}),[se,setSe]=useState({environment:"production",partnerId:"",partnerKey:"",shopId:"",accessToken:"",accessTokenExpiresAt:expiry()}),[sl,setSl]=useState(()=>{const now=Date.now();return{timeRangeField:"create_time",timeFrom:Math.floor((now-3600000)/1000),timeTo:Math.floor(now/1000)}});
 const load=useCallback(async()=>{setLoading(true);try{const[s,l]=await Promise.all([apiJson<Shopee>("/admin/marketplaces/providers/shopee"),apiJson<Lazada>("/admin/marketplaces/providers/lazada")]);setShopee(s);setLazada(l);if(s.config){setSc({...s.config,partnerKey:""});setSe(current=>({...current,environment:s.config!.environment,partnerId:s.config!.partnerId,partnerKey:""}))}if(l.config)setLc({appKey:l.config.appKey,appSecret:"",redirectUri:l.config.redirectUri||"",enabled:l.config.enabled});}catch(e){setMessage((e as{status?:number}).status===403?"Bạn không có quyền truy cập.":"Không thể tải cấu hình Marketplace.")}finally{setLoading(false)}},[]);
 useEffect(()=>{if(user?.role==="ADMIN")void Promise.resolve().then(load);else void Promise.resolve().then(()=>setLoading(false))},[user,load]);
 useEffect(()=>{const url=new URL(window.location.href);if(!url.searchParams.has("shopeeOAuth"))return;void Promise.resolve().then(()=>setMessage(oauthMessage()));url.searchParams.delete("shopeeOAuth");url.searchParams.delete("code");window.history.replaceState({},"",`${url.pathname}${url.search}${url.hash}`)},[]);
 if(user?.role!=="ADMIN")return <main className={styles.page}><EmptyState title="Không có quyền truy cập" description="Marketplace chỉ dành cho quản trị viên."/></main>;
 const post=<T,>(p:string,b?:unknown)=>apiJson<T>(p,{method:"POST",...(b?{headers:{"content-type":"application/json"},body:JSON.stringify(b)}:{})});
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}finally{setBusy(false)}};
 const sx=shopee.connections.find(x=>x.credentialSource==="EXTERNAL_IMPORT"),ox=shopee.connections.find(x=>x.credentialSource==="OAUTH"),lx=lazada.connections.find(x=>x.credentialSource==="EXTERNAL_IMPORT");
 const saveShopee=(e:FormEvent)=>{e.preventDefault();void run(async()=>{try{await apiJson("/admin/marketplaces/providers/shopee",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...sc,partnerKey:sc.partnerKey||undefined})});setModal(null);setMessage("Đã lưu cấu hình Shopee.");await load()}catch(x){setMessage(err(x,"SHOPEE_CONFIG_INVALID"))}})};
 const startShopee=()=>void run(async()=>{try{const r=await post<{authorizationUrl:string}>("/marketplaces/shopee/oauth/start");window.location.assign(r.authorizationUrl)}catch(x){setMessage(err(x,"SHOPEE_OAUTH_CONFIG_MISSING"))}});
 const saveShopeeExternal=(e:FormEvent)=>{e.preventDefault();void run(async()=>{try{await post("/admin/marketplaces/providers/shopee/external-token",{...se,partnerKey:se.partnerKey||undefined,accessTokenExpiresAt:new Date(se.accessTokenExpiresAt).toISOString()});setModal(null);setMessage("Đã lưu token Shopee external chỉ đọc.");await load()}catch(x){setMessage(err(x,"SHOPEE_EXTERNAL_CONFIG_INVALID"))}})};
 const testShopeeExternal=()=>void run(async()=>{try{await post("/admin/marketplaces/providers/shopee/external-test",{connectionId:sx?.id});setMessage("Cấu hình Shopee external sẵn sàng — chưa gọi provider live.")}catch(x){setMessage(err(x,"SHOPEE_EXTERNAL_CONFIG_INVALID"))}});
 const testShopee=()=>void run(async()=>{try{await post("/admin/marketplaces/providers/shopee/test");setMessage("Cấu hình OAuth Shopee sẵn sàng — chưa gọi provider live.")}catch(x){setMessage(err(x,"SHOPEE_CONFIG_INVALID"))}});
 const openShopeeLive=(connectionId:string)=>{setShopeeLiveConnectionId(connectionId);setModal("shopee-live")};
 const liveShopee=(e:FormEvent)=>{e.preventDefault();void run(async()=>{try{await post("/admin/marketplaces/providers/shopee/live-test",{connectionId:shopeeLiveConnectionId,...sl,pageSize:10});setModal(null);setMessage("Live Shopee PASS — chỉ đọc.");await load()}catch(x){setMessage(err(x,"SHOPEE_LIVE_TEST_FAILED"))}})};
 const saveLazada=(e:FormEvent)=>{e.preventDefault();void run(async()=>{try{await apiJson("/admin/marketplaces/providers/lazada",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...lc,appSecret:lc.appSecret||undefined,redirectUri:lc.redirectUri||undefined})});setModal(null);setMessage("Đã lưu App Key/App Secret Lazada an toàn.");await load()}catch(x){setMessage(err(x,"LAZADA_CONFIG_INVALID"))}})};
 const saveExternal=(e:FormEvent)=>{e.preventDefault();void run(async()=>{try{await post("/admin/marketplaces/providers/lazada/external-token",{...le,accessToken:le.accessToken||undefined,accessTokenExpiresAt:new Date(le.accessTokenExpiresAt).toISOString()});setLe({...le,accessToken:""});setModal(null);setMessage("Đã lưu token Lazada external chỉ đọc.");await load()}catch(x){setMessage(err(x,"LAZADA_EXTERNAL_CONFIG_INVALID"))}})};
 const structural=()=>void run(async()=>{try{await post("/admin/marketplaces/providers/lazada/test",{connectionId:lx?.id});setMessage("Cấu hình Lazada sẵn sàng — chưa kiểm tra live.")}catch(x){setMessage(err(x,"LAZADA_CONFIG_INVALID"))}});
 const live=(e:FormEvent)=>{e.preventDefault();void run(async()=>{try{const r=await post<{orderCount:number}>("/admin/marketplaces/providers/lazada/live-test",{connectionId:lx?.id});setModal(null);setMessage(`Live Lazada PASS — ${r.orderCount} đơn, một request chỉ đọc.`);await load()}catch(x){setMessage(err(x,"LAZADA_LIVE_TEST_FAILED"))}})};
 return <main className={styles.page}><PageHeader eyebrow="Quản trị tích hợp" title="Marketplace" description="Quản lý cấu hình API và kết nối sàn an toàn."/>{message&&<Alert tone={/(INVALID|FAILED|MISSING|EXPIRED)/.test(message)?"danger":"success"}>{message}</Alert>}{loading?<div className={styles.skeletons}><Skeleton/><Skeleton/></div>:<div className={styles.platformGrid}>
 <Card className={styles.providerCard}><Header name="Shopee" letter="S" ready={!!shopee.config}/><div className={styles.overview}><Info l="Môi trường" v={shopee.config?.environment||"Chưa chọn"}/><Info l="Partner ID" v={shopee.config?.partnerId||"Chưa cấu hình"}/><Info l="Partner Key" v={shopee.config?.partnerSecretConfigured?"Đã lưu an toàn":"Chưa cấu hình"}/><Info l="Khóa mã hóa" v={shopee.encryptionReady?"Sẵn sàng":"Chưa cấu hình"}/></div><div className={styles.modes}><Mode title="Kết nối chính thức bằng OAuth" text="Shopee trả Shop ID và Ecomkit lưu token ở phía máy chủ." badge={ox?"CONNECTED":"OAUTH MANAGED"}><div className={styles.statusRows}><Info l="Trạng thái" v={ox?"Đã kết nối":"Sẵn sàng ủy quyền"}/><Info l="Shop ID" v={ox?.externalShopId||"Tự động nhận sau ủy quyền"}/><Info l="Access Token" v={ox?.accessTokenConfigured?"Đã lưu an toàn":"Chưa có"}/><Info l="Refresh Token" v={ox?.refreshTokenConfigured?"Đã lưu an toàn":"Chưa có"}/><Info l="Hết hạn Access Token" v={ox?.accessTokenExpiresAt?new Date(ox.accessTokenExpiresAt).toLocaleString("vi-VN"):"Chưa có"}/><Info l="Refresh" v={ox?.refreshOwnership==="ECOMKIT"?"Ecomkit quản lý":"Chưa kích hoạt"}/></div><div className={styles.actions}><Button onClick={()=>setModal("shopee")}>Cấu hình OAuth</Button><Button variant="outline" disabled={!shopee.config?.partnerSecretConfigured||!shopee.config.redirectUri||!shopee.config.enabled||!shopee.encryptionReady} onClick={testShopee}>Kiểm tra cấu hình</Button><Button disabled={!shopee.config?.partnerSecretConfigured||!shopee.config.redirectUri||!shopee.config.enabled||!shopee.encryptionReady} onClick={startShopee}>{ox?"Ủy quyền lại":"Kết nối Shopee"}</Button><Button variant="secondary" disabled={!ox} onClick={()=>ox&&openShopeeLive(ox.id)}>Test Shopee API</Button></div><small className={styles.reason}>Ủy quyền cần Redirect URI được Shopee chấp thuận. Ecomkit không hiển thị token sau khi lưu.</small></Mode><Mode title="Kiểm tra local bằng token hệ thống ngoài" text="Chế độ chỉ đọc hiện có được giữ nguyên." badge="READ ONLY"><Info l="Shop" v={sx?.externalShopId||"Chưa cấu hình"}/><Info l="Access Token" v={sx?.accessTokenConfigured?"Đã lưu an toàn":"Chưa cấu hình"}/><div className={styles.actions}><Button onClick={()=>setModal("shopee-external")}>{sx?"Cập nhật token":"Nhập token external"}</Button><Button variant="outline" disabled={!sx} onClick={testShopeeExternal}>Kiểm tra cấu hình</Button><Button variant="secondary" disabled={!sx} onClick={()=>sx&&openShopeeLive(sx.id)}>Test Shopee API</Button></div></Mode></div></Card>
 <Card className={styles.providerCard}><Header name="Lazada" letter="L" ready={!!lazada.config}/><div className={styles.overview}><Info l="Khu vực" v="Vietnam"/><Info l="API" v="Production"/><Info l="App Key" v={lazada.config?.appKey||"Chưa cấu hình"}/><Info l="App Secret" v={lazada.config?.appSecretConfigured?"Đã lưu an toàn":"Chưa cấu hình"}/></div><div className={styles.modes}><Mode title="Kết nối chính thức bằng OAuth" text="Dành cho kết nối chính thức trong tương lai." badge="DEFERRED"><Info l="Redirect URI" v={lazada.config?.redirectUri||"Không bắt buộc lúc này"}/><div className={styles.actions}><Button onClick={()=>setModal("lazada-config")}>Cấu hình ứng dụng</Button><Button disabled>Kết nối Lazada (chưa bật)</Button></div></Mode><Mode title="Kiểm tra local bằng token hệ thống ngoài" text="Không cần domain, callback hoặc OAuth." badge="READ ONLY"><div className={styles.statusRows}><Info l="Seller ID" v={lx?.sellerId||"Chưa cấu hình"}/><Info l="Access Token" v={lx?.accessTokenConfigured?"Đã lưu an toàn":"Chưa cấu hình"}/><Info l="Nguồn credential" v={lx?"Hệ thống bên ngoài":"Chưa cấu hình"}/><Info l="Refresh" v={lx?"Hệ thống ngoài quản lý":"Không áp dụng"}/></div><Alert tone="warning">Ecomkit không tự refresh hoặc revoke token. Không nhập refresh token.</Alert><div className={styles.actions}><Button onClick={()=>{setLe({...le,sellerId:lx?.sellerId||""});setModal("lazada-external")}}>{lx?"Cập nhật token":"Nhập token external"}</Button><Button variant="outline" loading={busy} disabled={!lazada.config?.appSecretConfigured||!lx} onClick={structural}>Kiểm tra cấu hình</Button><Button variant="secondary" disabled={!lazada.config?.appSecretConfigured||!lx} onClick={()=>setModal("lazada-live")}>Test Lazada API</Button></div><small className={styles.reason}>Kiểm tra cấu hình không gọi Lazada. Test API gửi đúng một GetOrders, limit=1.</small></Mode></div></Card>
 <Card className={styles.placeholder}><Header name="TikTok Shop" letter="T" ready={false}/><p>Chưa triển khai.</p><Button disabled>Chưa triển khai</Button></Card></div>}
 <Dialog open={modal==="shopee"} title="Cấu hình OAuth Shopee" onClose={()=>setModal(null)}><form className={styles.form} onSubmit={saveShopee}><Field label="Môi trường"><select value={sc.environment} onChange={e=>setSc({...sc,environment:e.target.value})}><option value="sandbox">Sandbox</option><option value="production">Production</option></select></Field><Field label="Partner ID"><input required value={sc.partnerId} onChange={e=>setSc({...sc,partnerId:e.target.value})}/></Field><Field label="Partner Key" helper="Để trống nếu không thay đổi key đã mã hóa."><input type="password" autoComplete="new-password" required={!shopee.config?.partnerSecretConfigured} value={sc.partnerKey} onChange={e=>setSc({...sc,partnerKey:e.target.value})}/></Field><Field label="Redirect URI"><input required type="url" value={sc.redirectUri} onChange={e=>setSc({...sc,redirectUri:e.target.value})}/></Field><Actions busy={busy} close={()=>setModal(null)} label="Lưu cấu hình"/></form></Dialog>
 <Dialog open={modal==="shopee-external"} title="Token Shopee hệ thống ngoài · Chỉ đọc" onClose={()=>setModal(null)}><form className={styles.form} onSubmit={saveShopeeExternal}><Field label="Môi trường"><select value={se.environment} onChange={e=>setSe({...se,environment:e.target.value})}><option value="production">Production</option><option value="sandbox">Sandbox</option></select></Field><Field label="Partner ID"><input required value={se.partnerId} onChange={e=>setSe({...se,partnerId:e.target.value})}/></Field><Field label="Partner Key"><input type="password" required={!shopee.config?.partnerSecretConfigured} value={se.partnerKey} onChange={e=>setSe({...se,partnerKey:e.target.value})}/></Field><Field label="Shop ID"><input required value={se.shopId} onChange={e=>setSe({...se,shopId:e.target.value})}/></Field><Field label="Access Token"><input type="password" required value={se.accessToken} onChange={e=>setSe({...se,accessToken:e.target.value})}/></Field><Field label="Hết hạn lúc"><input type="datetime-local" required value={se.accessTokenExpiresAt} onChange={e=>setSe({...se,accessTokenExpiresAt:e.target.value})}/></Field><Actions busy={busy} close={()=>setModal(null)} label="Lưu token external"/></form></Dialog>
 <Dialog open={modal==="shopee-live"} title="Test Shopee API · Chỉ đọc" onClose={()=>setModal(null)}><form className={styles.form} onSubmit={liveShopee}><Field label="Trường thời gian"><select value={sl.timeRangeField} onChange={e=>setSl({...sl,timeRangeField:e.target.value})}><option value="create_time">create_time</option><option value="update_time">update_time</option></select></Field><Actions busy={busy} close={()=>setModal(null)} label="Gọi Get Order List"/></form></Dialog>
 <Dialog open={modal==="lazada-config"} title="Cấu hình ứng dụng Lazada" onClose={()=>setModal(null)}><form className={styles.form} onSubmit={saveLazada}><Field label="Khu vực"><input disabled value="Vietnam"/></Field><Field label="Môi trường API"><input disabled value="Production"/></Field><Field label="App Key"><input required value={lc.appKey} onChange={e=>setLc({...lc,appKey:e.target.value})}/></Field><Field label="App Secret" helper="Để trống nếu không thay đổi secret đã mã hóa."><input type="password" autoComplete="new-password" required={!lazada.config?.appSecretConfigured} value={lc.appSecret} onChange={e=>setLc({...lc,appSecret:e.target.value})}/></Field><Field label="Redirect URI (tùy chọn cho OAuth sau này)"><input type="url" value={lc.redirectUri} onChange={e=>setLc({...lc,redirectUri:e.target.value})}/></Field><Actions busy={busy} close={()=>setModal(null)} label="Lưu cấu hình Lazada"/></form></Dialog>
 <Dialog open={modal==="lazada-external"} title="Token Lazada hệ thống ngoài · Chỉ đọc" onClose={()=>setModal(null)}><form className={styles.form} onSubmit={saveExternal}><Alert tone="warning">Không cần domain, callback, OAuth hay refresh token.</Alert><Field label="Seller ID"><input required value={le.sellerId} onChange={e=>setLe({...le,sellerId:e.target.value})}/></Field><Field label="Access Token" helper={lx?"Để trống nếu chỉ cập nhật thời gian hết hạn.":undefined}><input type="password" autoComplete="new-password" required={!lx} value={le.accessToken} onChange={e=>setLe({...le,accessToken:e.target.value})}/></Field><Field label="Access Token hết hạn lúc"><input required type="datetime-local" value={le.accessTokenExpiresAt} onChange={e=>setLe({...le,accessTokenExpiresAt:e.target.value})}/></Field><Actions busy={busy} close={()=>setModal(null)} label="Lưu token external"/></form></Dialog>
 <Dialog open={modal==="lazada-live"} title="Test Lazada API · Chỉ đọc" onClose={()=>setModal(null)}><form className={styles.form} onSubmit={live}><Alert tone="warning">Gửi đúng một GetOrders, limit=1, cửa sổ 60 phút. Không item, polling, refresh hoặc Batch.</Alert><Info l="Seller ID" v={lx?.sellerId||"Chưa cấu hình"}/><Actions busy={busy} close={()=>setModal(null)} label="Gọi GetOrders một lần"/></form></Dialog>
 </main>}
function Header({name,letter,ready}:{name:string;letter:string;ready:boolean}){return <header className={styles.platformHeader}><div><span className={styles.logo}>{letter}</span><div><small>PLATFORM</small><h2>{name}</h2></div></div><StatusBadge status={ready?"PENDING":"NOT_CONFIGURED"} label={ready?"Đã cấu hình":"Chưa cấu hình"}/></header>}
function Info({l,v}:{l:string;v:string}){return <div className={styles.info}><span>{l}</span><strong>{v}</strong></div>}
function Mode({title,text,badge,children}:{title:string;text:string;badge:string;children:ReactNode}){return <section className={styles.mode}><header><div><h3>{title}</h3><p>{text}</p></div><span>{badge}</span></header>{children}</section>}
function Actions({busy,close,label}:{busy:boolean;close:()=>void;label:string}){return <div className={styles.formActions}><Button type="button" variant="ghost" onClick={close}>Hủy</Button><Button loading={busy}>{label}</Button></div>}
