import { BadRequestException, Injectable } from "@nestjs/common";
import { loadShopeeRuntimeConfig, ShopeeHttpClient } from "@ecomkit/shared";
import type { ShopeeResponse } from "@ecomkit/shared";
import { ShopeeTokenService, type ValidShopeeCredential } from "./shopee-token.service.js";

export type ShopeeTimeRangeField = "create_time" | "update_time";
export type ShopeeOrderStatus = "UNPAID" | "READY_TO_SHIP" | "PROCESSED" | "SHIPPED" | "COMPLETED" | "IN_CANCEL" | "CANCELLED" | "INVOICE_PENDING";
export type ShopeeOrderListItem = { order_sn: string; order_status?: ShopeeOrderStatus; booking_sn?: string };
export type ShopeeOrderListResponse = { more?: boolean; next_cursor?: string; order_list?: ShopeeOrderListItem[] };
export type ShopeeOrderItem = { item_id?: number; item_name?: string; item_sku?: string; model_id?: number; model_name?: string; model_sku?: string; model_quantity_purchased?: number; model_original_price?: number; model_discounted_price?: number; order_item_id?: number; line_item_id?: number };
export type ShopeeOrderDetail = { order_sn: string; region?: string; currency?: string; cod?: number; total_amount?: number; order_status?: string; create_time?: number; update_time?: number; message_to_seller?: string; payment_method?: string; shipping_carrier?: string; recipient_address?: Record<string, unknown>; item_list?: ShopeeOrderItem[]; package_list?: Record<string, unknown>[] };
export type ShopeeOrderDetailResponse = { order_list?: ShopeeOrderDetail[] };
type ShopClient = { requestShop<T>(input: { operation: string; apiPath: string; method: "GET"; accessToken: string; shopId: string; query: Record<string, string | number | boolean | undefined> }): Promise<ShopeeResponse<T>> };
const MAX_WINDOW_SECONDS = 15 * 24 * 60 * 60;

export class ShopeeOrderProtocolError extends Error { constructor(public readonly safe: { code: string; requestId?: string; externalCode?: string; message: string }) { super(safe.message); } }
export function validateShopeeWindow(field: ShopeeTimeRangeField, timeFrom: number, timeTo: number): void { if ((field !== "create_time" && field !== "update_time") || !Number.isInteger(timeFrom) || !Number.isInteger(timeTo) || timeFrom >= timeTo || timeTo - timeFrom > MAX_WINDOW_SECONDS) throw new BadRequestException({ errorCode: "SHOPEE_ORDER_WINDOW_INVALID", message: "Shopee order time window is invalid." }); }
export function splitShopeeWindows(timeFrom: number, timeTo: number): Array<{ timeFrom: number; timeTo: number }> { if (!Number.isInteger(timeFrom) || !Number.isInteger(timeTo) || timeFrom >= timeTo) throw new BadRequestException({ errorCode: "SHOPEE_ORDER_WINDOW_INVALID", message: "Shopee order time window is invalid." }); const result = []; for (let start = timeFrom; start < timeTo; start += MAX_WINDOW_SECONDS) result.push({ timeFrom: start, timeTo: Math.min(start + MAX_WINDOW_SECONDS, timeTo) }); return result; }
export function batchShopeeOrderSn(orderSns: readonly string[]): string[][] { if (!orderSns.length) throw new BadRequestException({ errorCode: "SHOPEE_ORDER_DETAIL_INPUT_INVALID", message: "At least one Shopee order identifier is required." }); return Array.from({ length: Math.ceil(orderSns.length / 50) }, (_, index) => [...orderSns.slice(index * 50, index * 50 + 50)]); }

@Injectable()
export class ShopeeOrderClient {
  constructor(private readonly tokens: ShopeeTokenService, private readonly clientFactory: () => ShopClient = () => new ShopeeHttpClient(loadShopeeRuntimeConfig())) {}
  private async credential(connectionId: string): Promise<ValidShopeeCredential> { return this.tokens.ensureValidAccessToken(connectionId); }
  async listOrders(connectionId: string, input: { timeRangeField: ShopeeTimeRangeField; timeFrom: number; timeTo: number; pageSize?: number; cursor?: string; orderStatus?: ShopeeOrderStatus; responseOptionalFields?: string; requestOrderStatusPending?: boolean }): Promise<{ orders: ShopeeOrderListItem[]; more: boolean; nextCursor?: string; requestId?: string }> {
    validateShopeeWindow(input.timeRangeField, input.timeFrom, input.timeTo); const pageSize = input.pageSize ?? 100; if (!Number.isInteger(pageSize) || pageSize < 1 || pageSize > 100) throw new BadRequestException({ errorCode: "SHOPEE_ORDER_PAGE_SIZE_INVALID", message: "Shopee page size is invalid." });
    const credential = await this.credential(connectionId); const result = await this.clientFactory().requestShop<ShopeeOrderListResponse>({ operation: "SHOPEE_ORDER_LIST", apiPath: "/api/v2/order/get_order_list", method: "GET", accessToken: credential.accessToken, shopId: credential.shopId, query: { time_range_field: input.timeRangeField, time_from: input.timeFrom, time_to: input.timeTo, page_size: pageSize, cursor: input.cursor, order_status: input.orderStatus, response_optional_fields: input.responseOptionalFields, request_order_status_pending: input.requestOrderStatusPending } });
    if (result.error) throw new ShopeeOrderProtocolError({ code: "SHOPEE_ORDER_PROVIDER_ERROR", requestId: result.request_id, externalCode: result.error, message: result.message ?? "Shopee order request failed." }); const response = result.response ?? {}; const more = response.more === true, nextCursor = response.next_cursor;
    if (more && !nextCursor) throw new ShopeeOrderProtocolError({ code: "SHOPEE_ORDER_CURSOR_MISSING", requestId: result.request_id, message: "Shopee pagination response is invalid." }); return { orders: response.order_list ?? [], more, ...(nextCursor ? { nextCursor } : {}), ...(result.request_id ? { requestId: result.request_id } : {}) };
  }
  async listAllInWindow(connectionId: string, input: Omit<Parameters<ShopeeOrderClient["listOrders"]>[1], "cursor">): Promise<ShopeeOrderListItem[]> { const all: ShopeeOrderListItem[] = [], seen = new Set<string>(); let cursor: string | undefined; do { const page = await this.listOrders(connectionId, { ...input, cursor }); if (page.more && (!page.nextCursor || seen.has(page.nextCursor))) throw new ShopeeOrderProtocolError({ code: "SHOPEE_ORDER_CURSOR_REPEATED", message: "Shopee pagination response repeated a cursor." }); all.push(...page.orders); if (page.nextCursor) seen.add(page.nextCursor); cursor = page.more ? page.nextCursor : undefined; } while (cursor); return all; }
  async getOrderDetails(connectionId: string, orderSns: readonly string[], optional: { responseOptionalFields?: string; requestOrderStatusPending?: boolean } = {}): Promise<{ orders: ShopeeOrderDetail[]; missingOrderSns: string[] }> { const received = new Map<string, ShopeeOrderDetail>(); for (const batch of batchShopeeOrderSn(orderSns)) { const credential = await this.credential(connectionId); const result = await this.clientFactory().requestShop<ShopeeOrderDetailResponse>({ operation: "SHOPEE_ORDER_DETAIL", apiPath: "/api/v2/order/get_order_detail", method: "GET", accessToken: credential.accessToken, shopId: credential.shopId, query: { order_sn_list: batch.join(","), response_optional_fields: optional.responseOptionalFields, request_order_status_pending: optional.requestOrderStatusPending } }); if (result.error) throw new ShopeeOrderProtocolError({ code: "SHOPEE_ORDER_PROVIDER_ERROR", requestId: result.request_id, externalCode: result.error, message: result.message ?? "Shopee order request failed." }); for (const order of result.response?.order_list ?? []) { if (received.has(order.order_sn)) throw new ShopeeOrderProtocolError({ code: "SHOPEE_ORDER_DETAIL_DUPLICATE", message: "Shopee returned duplicate order detail." }); received.set(order.order_sn, order); } } return { orders: [...received.values()], missingOrderSns: orderSns.filter((id) => !received.has(id)) }; }
}
