"use client";

import { ChangeEvent, useEffect, useState } from "react";
import Link from "next/link";
import { apiFetch } from "../../../lib/api";
import styles from "./workflow.module.css";

type Status = { processingStatus: "PENDING"|"PROCESSING"|"SUCCESS"|"WARNING"|"ERROR"; currentStage?: string; progress?: number; lastError?: string | null };
const label: Record<Status["processingStatus"], string> = { PENDING:"Đang chờ xử lý", PROCESSING:"Đang xử lý", SUCCESS:"Hoàn tất", WARNING:"Hoàn tất có cảnh báo", ERROR:"Có lỗi" };
export default function NewBatchPage(){const [batchId,setBatchId]=useState("");const [excel,setExcel]=useState<File|null>(null);const [pdfs,setPdfs]=useState<File[]>([]);const [uploading,setUploading]=useState(false);const [processing,setProcessing]=useState(false);const [status,setStatus]=useState<Status|null>(null);const [message,setMessage]=useState("");
useEffect(()=>{if(!batchId||!processing)return;let alive=true;const timer=window.setInterval(async()=>{const r=await apiFetch(`/batches/${batchId}/processing-status`);if(!r.ok)return;const next=await r.json() as Status;if(!alive)return;setStatus(next);if(["SUCCESS","WARNING","ERROR"].includes(next.processingStatus))setProcessing(false)},2500);return()=>{alive=false;window.clearInterval(timer)}},[batchId,processing]);
const create=async()=>{setMessage("");const r=await apiFetch("/batches",{method:"POST"});if(!r.ok){setMessage("Không thể tạo phiên xử lý. Vui lòng thử lại.");return}const b=await r.json() as {id:string};setBatchId(b.id);setStatus({processingStatus:"PENDING"});setMessage("Đã tạo phiên xử lý. Hãy tải các file nguồn.")};
const upload=async()=>{if(!batchId||!excel||!pdfs.length)return;setUploading(true);setMessage("");try{const form=new FormData();form.append("files",excel);pdfs.forEach(file=>form.append("files",file));const r=await apiFetch(`/batches/${batchId}/files`,{method:"POST",body:form});if(!r.ok){setMessage("Không thể tải file. Kiểm tra lại định dạng rồi thử lại.");return}setMessage("Tải file thành công. Bạn có thể bắt đầu xử lý.")}finally{setUploading(false)}};
const process=async()=>{if(!batchId)return;setMessage("");const r=await apiFetch(`/batches/${batchId}/process`,{method:"POST"});if(r.status===202){setProcessing(true);setStatus({processingStatus:"PENDING"});setMessage("Batch đã được đưa vào hàng đợi.");return}const body=await r.json().catch(()=>null) as {message?:string}|null;setMessage(body?.message??"Không thể bắt đầu xử lý. Vui lòng thử lại.")};
const pickExcel=(e:ChangeEvent<HTMLInputElement>)=>setExcel(e.target.files?.[0]??null);const pickPdf=(e:ChangeEvent<HTMLInputElement>)=>setPdfs(Array.from(e.target.files??[]));const ready=Boolean(batchId&&excel&&pdfs.length);
return <main className={styles.page}><header><p className={styles.brand}>Ecomkit - Vui Khỏe</p><h1>Xử lý đơn hàng</h1><p>Thực hiện theo thứ tự để hệ thống đối chiếu dữ liệu Excel và PDF.</p></header><section className={styles.steps}><article><h2>1. Tạo phiên xử lý</h2><button onClick={()=>void create()} disabled={Boolean(batchId)}>Tạo Batch</button>{batchId&&<code>{batchId}</code>}</article><article><h2>2. Chọn file nguồn</h2><label>Excel (.xlsx)<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={!batchId} onChange={pickExcel}/>{excel&&<span>{excel.name}</span>}</label><label>PDF (.pdf)<input type="file" accept=".pdf,application/pdf" multiple disabled={!batchId} onChange={pickPdf}/>{pdfs.map(file=><span key={file.name}>{file.name}</span>)}</label><button onClick={()=>void upload()} disabled={!ready||uploading}>{uploading?"Đang tải file...":"Tải file"}</button></article><article><h2>3. Bắt đầu xử lý</h2><button onClick={()=>void process()} disabled={!ready||uploading||processing}>Bắt đầu xử lý</button><p>Hệ thống sẽ tự đọc Excel, PDF và đối chiếu mã đơn sàn.</p></article><article><h2>4. Theo dõi trạng thái</h2>{status?<><strong className={styles[status.processingStatus.toLowerCase()]}>{label[status.processingStatus]}</strong><p>{status.progress??0}% · {status.currentStage??"pending"}</p>{status.processingStatus==="SUCCESS"&&<Link href={`/batches/${batchId}/results`}>Xem kết quả</Link>}{status.processingStatus==="ERROR"&&<Link href={`/batches/${batchId}/errors`}>Xem lỗi</Link>}</>:<p>Trạng thái sẽ hiển thị sau khi bắt đầu xử lý.</p>}</article></section>{message&&<p className={styles.message} role="status">{message}</p>}</main>}
