"use client";
import { ChangeEvent,useEffect,useRef,useState } from "react";
import { Alert,AppIcon,Button,ButtonLink,Card,PageHeader,StatusBadge } from "../../../components/ui/ui";
import { apiFetch } from "../../../lib/api";
import styles from "./workflow.module.css";
type Status={processingStatus:"PENDING"|"PROCESSING"|"SUCCESS"|"WARNING"|"ERROR";currentStage?:string;progress?:number;lastError?:string|null};
const labels:Record<Status["processingStatus"],string>={PENDING:"Đang chờ xử lý",PROCESSING:"Đang xử lý",SUCCESS:"Hoàn tất",WARNING:"Hoàn tất có cảnh báo",ERROR:"Có lỗi"};
const size=(value:number)=>value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`;
export default function NewBatchPage(){const[batchId,setBatchId]=useState(""),[excel,setExcel]=useState<File|null>(null),[pdfs,setPdfs]=useState<File[]>([]),[uploading,setUploading]=useState(false),[uploaded,setUploaded]=useState(false),[processing,setProcessing]=useState(false),[status,setStatus]=useState<Status|null>(null),[message,setMessage]=useState("");const excelRef=useRef<HTMLInputElement>(null),pdfRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!batchId||!processing)return;let alive=true;const timer=window.setInterval(async()=>{const response=await apiFetch(`/batches/${batchId}/processing-status`);if(!response.ok)return;const next=await response.json() as Status;if(!alive)return;setStatus(next);if(["SUCCESS","WARNING","ERROR"].includes(next.processingStatus))setProcessing(false)},2500);return()=>{alive=false;window.clearInterval(timer)}},[batchId,processing]);
 const create=async()=>{setMessage("");const response=await apiFetch("/batches",{method:"POST"});if(!response.ok)return setMessage("Không thể tạo phiên xử lý. Vui lòng thử lại.");const batch=await response.json() as{id:string};setBatchId(batch.id);setStatus({processingStatus:"PENDING"});setMessage("Đã tạo phiên xử lý. Hãy chọn file nguồn.")};
 const upload=async()=>{if(!batchId||!excel||!pdfs.length)return;setUploading(true);setMessage("");try{const form=new FormData();form.append("files",excel);pdfs.forEach(file=>form.append("files",file));const response=await apiFetch(`/batches/${batchId}/files`,{method:"POST",body:form});if(!response.ok)return setMessage("Không thể tải file. Kiểm tra định dạng và dung lượng rồi thử lại.");setUploaded(true);setMessage("Tải file thành công. Phiên xử lý đã sẵn sàng.")}finally{setUploading(false)}};
 const process=async()=>{if(!batchId)return;setMessage("");const response=await apiFetch(`/batches/${batchId}/process`,{method:"POST"});if(response.status===202){setProcessing(true);setStatus({processingStatus:"PENDING"});return setMessage("Batch đã được đưa vào hàng đợi.")}const body=await response.json().catch(()=>null) as{message?:string}|null;setMessage(body?.message??"Không thể bắt đầu xử lý. Vui lòng thử lại.")};
 const pickExcel=(event:ChangeEvent<HTMLInputElement>)=>{setExcel(event.target.files?.[0]??null);setUploaded(false)},pickPdf=(event:ChangeEvent<HTMLInputElement>)=>{setPdfs(Array.from(event.target.files??[]));setUploaded(false)};const chosen=Boolean(batchId&&excel&&pdfs.length),terminal=status&&["SUCCESS","WARNING","ERROR"].includes(status.processingStatus);
 return <main className={styles.page}><PageHeader eyebrow="Quy trình xử lý" title="Xử lý đơn hàng" description="Tải một file Excel và các file PDF để hệ thống đọc, đối chiếu chính xác theo mã đơn sàn."/>{message&&<Alert tone={status?.processingStatus==="ERROR"?"danger":"success"}>{message}</Alert>}
  <div className={styles.layout}><section className={styles.workflow}><Card className={styles.step}><Step number="1" title="Tạo phiên xử lý" done={Boolean(batchId)}/><p>Mỗi lần xử lý được lưu thành một Batch để theo dõi và xem lại.</p><Button onClick={()=>void create()} disabled={Boolean(batchId)}>Tạo Batch</Button>{batchId&&<div className={styles.batchId}><span>Batch ID</span><code>{batchId}</code></div>}</Card>
   <Card className={styles.step}><Step number="2" title="Chọn file nguồn" done={uploaded}/><p>Tối đa 25 MB/file, 100 file và chỉ một file Excel.</p><div className={styles.uploadGrid}><FilePicker title="File Excel" description="Kéo thả hoặc chọn một file .xlsx" disabled={!batchId} onClick={()=>excelRef.current?.click()} onDrop={files=>{const file=files.find(item=>item.name.toLowerCase().endsWith(".xlsx"));if(file){setExcel(file);setUploaded(false)}}}><input ref={excelRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={!batchId} onChange={pickExcel}/>{excel&&<FileRow file={excel} onRemove={()=>{setExcel(null);setUploaded(false)}}/>}</FilePicker><FilePicker title="File PDF" description="Kéo thả hoặc chọn các file .pdf" disabled={!batchId} onClick={()=>pdfRef.current?.click()} onDrop={files=>{const selected=files.filter(item=>item.name.toLowerCase().endsWith(".pdf"));if(selected.length){setPdfs(selected);setUploaded(false)}}}><input ref={pdfRef} type="file" accept=".pdf,application/pdf" multiple disabled={!batchId} onChange={pickPdf}/>{pdfs.map((file,index)=><FileRow key={`${file.name}-${index}`} file={file} onRemove={()=>{setPdfs(pdfs.filter((_,item)=>item!==index));setUploaded(false)}}/>)}</FilePicker></div><Button variant="secondary" loading={uploading} onClick={()=>void upload()} disabled={!chosen||uploaded}><AppIcon name="upload"/>Tải file lên</Button></Card>
   <Card className={styles.step}><Step number="3" title="Bắt đầu xử lý" done={Boolean(terminal&&status.processingStatus!=="ERROR")}/><p>Hệ thống đọc Excel/PDF và đối chiếu chính xác mã đơn sàn.</p><Button loading={processing} onClick={()=>void process()} disabled={!uploaded||processing}>Xử lý đơn hàng</Button></Card></section>
   <aside><Card className={styles.statusCard}><h2>Trạng thái Batch</h2>{status?<><StatusBadge status={status.processingStatus} label={labels[status.processingStatus]}/><dl><dt>Công đoạn</dt><dd>{status.currentStage??"Chưa bắt đầu"}</dd>{typeof status.progress==="number"&&<><dt>Tiến độ</dt><dd>{status.progress}%</dd></>}</dl>{status.lastError&&<Alert tone="danger">{status.lastError}</Alert>}<div className={styles.resultActions}>{status.processingStatus==="SUCCESS"||status.processingStatus==="WARNING"?<><ButtonLink href={`/batches/${batchId}/results`}>Xem kết quả</ButtonLink><ButtonLink href={`/batches/${batchId}/errors`} variant="outline">Xem lỗi & cảnh báo</ButtonLink></>:status.processingStatus==="ERROR"?<ButtonLink href={`/batches/${batchId}/errors`} variant="danger">Xem lỗi</ButtonLink>:null}</div></>:<p className={styles.muted}>Trạng thái sẽ xuất hiện sau khi tạo Batch.</p>}</Card></aside></div>
 </main>}
function Step({number,title,done}:{number:string;title:string;done:boolean}){return <header className={styles.stepHeader}><span className={done?styles.done:""}>{done?<AppIcon name="check"/>:number}</span><h2>{title}</h2></header>}
function FilePicker({title,description,disabled,onClick,onDrop,children}:{title:string;description:string;disabled:boolean;onClick:()=>void;onDrop:(files:File[])=>void;children:React.ReactNode}){return <div className={styles.picker} onDragOver={event=>{if(!disabled)event.preventDefault()}} onDrop={event=>{if(disabled)return;event.preventDefault();onDrop(Array.from(event.dataTransfer.files))}}><button type="button" disabled={disabled} onClick={onClick}><AppIcon name="upload" size={24}/><strong>{title}</strong><span>{description}</span></button>{children}</div>}
function FileRow({file,onRemove}:{file:File;onRemove:()=>void}){return <div className={styles.fileRow}><AppIcon name="file"/><div><strong>{file.name}</strong><small>{size(file.size)}</small></div><button type="button" onClick={onRemove} aria-label={`Bỏ ${file.name}`}>×</button></div>}
